# Generated by Django 4.1.5 on 2023-02-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('topspeed', models.CharField(max_length=100)),
            ],
        ),
    ]
