# Generated by Django 4.1.5 on 2023-02-15 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_alter_car_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='topspeed',
            new_name='ratings',
        ),
    ]
